# Random 

### Rand()

In [21]:
import numpy as np

var = np.random.rand(4)
print(var)

[0.42872986 0.00627626 0.23383311 0.97496777]


In [22]:
var1 = np.random.rand(3,5)
print(var1)

[[0.27068032 0.16856368 0.2490428  0.33918812 0.0083395 ]
 [0.34942457 0.55739961 0.64652137 0.11011689 0.3116893 ]
 [0.86351609 0.96278129 0.82458352 0.2585005  0.47462466]]


### Randn()

In [23]:
var2 = np.random.randn(5,6)
print(var2)

[[ 1.39944348 -1.24350178  0.91773753 -0.22208251  0.24159759 -0.25254937]
 [-1.43057044  1.54666041 -0.47992719 -0.47349326 -0.87135905 -0.59247794]
 [-1.50539959  0.47274584 -0.04610349 -0.15461181 -2.45303249  0.20240958]
 [-0.59777345  1.07251498 -0.33047587 -0.62509392 -3.10275435 -0.36340137]
 [-0.61471903 -0.7576559  -0.23715091 -1.19749317  0.51868928  1.00624078]]


### Ranf()

In [26]:
var3 = np.random.ranf(4)
print(var3)

[0.40366454 0.48784048 0.87632635 0.4511243 ]


### Randint

In [28]:
var4 = np.random.randint(0,20,5)   #randint(min,max,total value)
print(var4)

[ 9 16 11 13 12]
