# Code

In [2]:
import numpy as np

var = np.array([[1,2],[1,2]])

print(var)
print()
print(var.shape)

[[1 2]
 [1 2]]

(2, 2)


In [4]:
var1 = np.array([1,2,3,4],ndmin=4)

print(var1)
print(var1.ndim)
print()
print(var1.shape)


[[[[1 2 3 4]]]]
4

(1, 1, 1, 4)


# Reshape

In [12]:
var2 = np.array([1,2,3,4,5,6])
print(var2)
print(var2.ndim)
print()

x = var2.reshape(3,2)

print(x)
print(x.ndim)

[1 2 3 4 5 6]
1

[[1 2]
 [3 4]
 [5 6]]
2


In [14]:
var3 = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(var3)
print(var3.ndim)
print()

x1 = var3.reshape(2,3,2)

print(x1)
print(x1.ndim)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
1

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
3


In [15]:
var3 = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(var3)
print(var3.ndim)
print()

x1 = var3.reshape(2,3,2)

print(x1)
print(x1.ndim)
print()

one = x1.reshape(-1)
print(one)
print(one.ndim)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
1

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
3

[ 1  2  3  4  5  6  7  8  9 10 11 12]
1
