# Broadcasting

In [18]:
import numpy as np

var1 = np.array([1,2,3,4])
print(var1)
print(var1.shape)
print()

var2 = np.array([1,2,3,4])
print(var2)
print(var2.shape)
print()

print(var1 + var2)

[1 2 3 4]
(4,)

[1 2 3 4]
(4,)

[2 4 6 8]


In [19]:
var3 = np.array([1,2,3])
print(var3)
print(var3.shape)
print()

var4 = np.array([[1],[2],[3]])
print(var4)
print(var4.shape)
print()

print(var3 + var4)

[1 2 3]
(3,)

[[1]
 [2]
 [3]]
(3, 1)

[[2 3 4]
 [3 4 5]
 [4 5 6]]


In [20]:
x = np.array([[1],[2]])
print(x)
print(x.shape)
print()

y = np.array([[1,2,3],[4,5,6]])
print(y)
print(y.shape)
print()

print(x+y)

[[1]
 [2]]
(2, 1)

[[1 2 3]
 [4 5 6]]
(2, 3)

[[2 3 4]
 [6 7 8]]
