# Data Type

### Integer

In [44]:
import numpy as np

var = np.array([1,2,3,4,5])
print("Data Type :",var.dtype)


Data Type : int64


### Float

In [45]:
var2 = np.array([1.0,1.2,1.5,1.8,4.2,2.1])
print("Data Type :",var2.dtype)

Data Type : float64


### String

In [46]:
var3 = np.array(["Apple","Mango","Banana","Strawberry","Grapes"])
print("Data Type :",var3.dtype)

Data Type : <U10


In [47]:
var4 = np.array(["A","S","B","T"])
print("Data Type :",var4.dtype)

Data Type : <U1


### String and Integer

In [48]:
var5 = np.array(["A","S","B","T",1,2,3,4])
print("Data Type :",var5.dtype)

Data Type : <U21


# Conversion Of Data Types

### Integer To Integer

In [49]:
x = np.array([1,2,3,4],dtype = np.int8)
print("Data Type :",x.dtype)

Data Type : int8


### Integer To Float

In [50]:
x1 = np.array([1,2,3,4],dtype = "f")
print("Data Type :",x1.dtype)
print(x1)

Data Type : float32
[1. 2. 3. 4.]


In [51]:
# As a function

x2 = np.array([1,2,3,4])

new = np.float32(x2)

print("Data Type :",x2.dtype)
print("Data Type :",new.dtype)

print(x2)
print(new)

Data Type : int64
Data Type : float32
[1 2 3 4]
[1. 2. 3. 4.]


### Integer to Float to Integer

In [52]:
x3 = np.array([1,2,3,4])

new = np.float32(x3)
new_one = np.int64(x3)

print("Data Type :",x3.dtype)
print("Data Type :",new.dtype)
print("Data Type :",new_one.dtype)

print(x3)
print(new)
print(new_one)

Data Type : int64
Data Type : float32
Data Type : int64
[1 2 3 4]
[1. 2. 3. 4.]
[1 2 3 4]


### Directly Conversion

In [53]:
x4 = np.array([1,2,3,4])

new_1 = x3.astype(float)

print(x4)
print(new_1)

[1 2 3 4]
[1. 2. 3. 4.]
