# Zeros


In [1]:
import numpy as np

arr_zero = np.zeros(4)

print(arr_zero)

[0. 0. 0. 0.]


In [5]:
import numpy as np

arr_zero = np.zeros(4)
arr_zero1 = np.zeros((3,4))

print(arr_zero)
print()
print(arr_zero1)

[0. 0. 0. 0.]

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


# Ones


In [6]:
arr_one = np.ones(4)

print(arr_one)

[1. 1. 1. 1.]


# Empty Array

In [7]:
arr_em = np.empty(4)

print(arr_em)

[1. 1. 1. 1.]


# Range

In [9]:
arr_rn = np.arange(4)
print(arr_rn)

[0 1 2 3]


# Diagonal

In [10]:
arr_dia = np.eye(3)
print(arr_dia)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [14]:
arr_dia1 = np.eye(3,5)
print(arr_dia1)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]


# Linspace

In [15]:
arr_lin = np.linspace(0,10,num=5)
print(arr_lin)

[ 0.   2.5  5.   7.5 10. ]
