# Arithmetic Operations 

### One Dimensional Array

In [87]:
import numpy as np 

var = np.array([1,2,3,4])

varadd = np.add(var,3)

print(varadd)

[4 5 6 7]


In [88]:
var = np.array([1,2,3,4])
var1 = np.array([5,6,7,8])

varadd_1 = np.add(var,var1)

print(varadd_1)

[ 6  8 10 12]


In [89]:
var = np.array([1,2,3,4])

varsubtract = np.subtract(var,3)

print(varsubtract)

[-2 -1  0  1]


In [90]:
var = np.array([1,2,3,4])
var1 = np.array([5,6,7,8])

varsubtarct_1 = np.subtract(var,var1)

print(varsubtarct_1)

[-4 -4 -4 -4]


In [91]:
var = np.array([1,2,3,4])

varmultiply = np.multiply(var,3)

print(varmultiply)

[ 3  6  9 12]


In [92]:
var = np.array([1,2,3,4])

vardivide = np.divide(var,3)

print(vardivide)

[0.33333333 0.66666667 1.         1.33333333]


In [93]:
var = np.array([1,2,3,4])

varmod = np.mod(var,3)

print(varmod)

[1 2 0 1]


In [94]:
var = np.array([1,2,3,4])

varpower = np.power(var,3)

print(varpower )

[ 1  8 27 64]


In [95]:
var = np.array([1,2,3,4])

varreciprocal = np.reciprocal(var)

print(varreciprocal)

[1 0 0 0]


### Two Dimensional Array

In [96]:
var2 = np.array([[1,2,3,4],[5,6,7,8]])

varadd_2 = np.add(var2,6)

print(varadd_2)

[[ 7  8  9 10]
 [11 12 13 14]]


In [97]:
var3 = np.array([[10,20,30,40],[50,60,70,80]])
var4 = np.array([[11,12,13,14],[15,16,17,18]])

varadd_3 = np.add(var3,var4)

print(var3)
print()
print(var4)
print()
print(varadd_3)

[[10 20 30 40]
 [50 60 70 80]]

[[11 12 13 14]
 [15 16 17 18]]

[[21 32 43 54]
 [65 76 87 98]]


In [98]:
var2 = np.array([[1,2,3,4],[5,6,7,8]])

varsubtract_2 = np.subtract(var2,6)

print(varsubtract_2)

[[-5 -4 -3 -2]
 [-1  0  1  2]]


In [99]:
var3 = np.array([[10,20,30,40],[50,60,70,80]])
var4 = np.array([[11,12,13,14],[15,16,17,18]])

varsub_3 = np.subtract(var3,var4)

print(var3)
print()
print(var4)
print()
print(varsub_3)

[[10 20 30 40]
 [50 60 70 80]]

[[11 12 13 14]
 [15 16 17 18]]

[[-1  8 17 26]
 [35 44 53 62]]


In [100]:
var2 = np.array([[1,2,3,4],[5,6,7,8]])

varmultiply_1 = np.multiply(var2,6)

print(varmultiply_1)

[[ 6 12 18 24]
 [30 36 42 48]]


In [101]:
var3 = np.array([[10,20,30,40],[50,60,70,80]])
var4 = np.array([[11,12,13,14],[15,16,17,18]])

varmultiply_3 = np.multiply(var3,var4)

print(var3)
print()
print(var4)
print()
print(varmultiply_3)

[[10 20 30 40]
 [50 60 70 80]]

[[11 12 13 14]
 [15 16 17 18]]

[[ 110  240  390  560]
 [ 750  960 1190 1440]]


In [102]:
var2 = np.array([[1,2,3,4],[5,6,7,8]])

vardivide_1 = np.divide(var2,6)

print(vardivide_1)

[[0.16666667 0.33333333 0.5        0.66666667]
 [0.83333333 1.         1.16666667 1.33333333]]


In [103]:
var3 = np.array([[10,20,30,40],[50,60,70,80]])
var4 = np.array([[11,12,13,14],[15,16,17,18]])

vardivide_3 = np.divide(var3,var4)

print(var3)
print()
print(var4)
print()
print(vardivide_3)

[[10 20 30 40]
 [50 60 70 80]]

[[11 12 13 14]
 [15 16 17 18]]

[[0.90909091 1.66666667 2.30769231 2.85714286]
 [3.33333333 3.75       4.11764706 4.44444444]]


In [104]:
var2 = np.array([[1,2,3,4],[5,6,7,8]])

varmod_1 = np.mod(var2,6)

print(varmod_1)

[[1 2 3 4]
 [5 0 1 2]]


In [105]:
var2 = np.array([[1,2,3,4],[5,6,7,8]])

varpower_1 = np.power(var2,6)

print(varpower_1)

[[     1     64    729   4096]
 [ 15625  46656 117649 262144]]


In [106]:
var2 = np.array([[1,2,3,4],[5,6,7,8]])

varreciprocal_1 = np.reciprocal(var2)

print(varreciprocal_1)

[[1 0 0 0]
 [0 0 0 0]]
