### Array

In [2]:
import numpy as np

x =[1,2,3,4]
y = np.array(x)
print(y)

[1 2 3 4]


In [4]:
import numpy as np

x =[1,2,3,4]
y = np.array(x)

y

array([1, 2, 3, 4])

In [6]:
import numpy as np

x =[1,2,3,4]
y = np.array(x)
print(y)

print(type(y))

[1 2 3 4]
<class 'numpy.ndarray'>


In [9]:
l = []

for i in range (1,5):
    int_1 = input("enter :")
    l.append(int_1)

print(np.array(l))

['10' '57' '72' '100']


In [10]:
import numpy as np

x =[1,2,3,4]
y = np.array(x)
print(y)
print(y.ndim)

[1 2 3 4]
1


In [11]:
ar2 = np.array([[1,2,3,4],[5,6,7,8]])
print(ar2)
print(ar2.ndim)


[[1 2 3 4]
 [5 6 7 8]]
2


In [12]:
ar3 = np.array([[[1,2,3],[4,5,6],[7,8,9],[10,11,12]]])
print(ar3)
print(ar3.ndim)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [10 11 12]]]
3


In [16]:
arn = np.array([1,2,3],ndmin = 10 )
print(arn)
print(arn.ndim)

[[[[[[[[[[1 2 3]]]]]]]]]]
10
